services:
  api:
    container_name: cee-scheduler-api
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: >
      uvicorn backend.app.main:app
      --host 0.0.0.0
      --port 8000
      --log-level info
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    env_file:
      - .env
    restart: unless-stopped

  api-dev:
    container_name: cee-scheduler-api-dev
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: >
      uvicorn backend.app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --log-level debug
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./data:/data
    env_file:
      - .env
    restart: unless-stopped
